"""initial schema

Revision ID: bd47890f343e
Revises: 
Create Date: 2026-06-13 11:54:49.627584
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'bd47890f343e'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealer_accounts',
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('dealership_name', sa.Text(), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('default_city', sa.Text(), nullable=True),
    sa.Column('default_province', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('listings',
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('source_listing_id', sa.Text(), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('dedupe_key', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'canonical_url')
    )
    op.create_table('search_runs',
    sa.Column('search_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('natural_language_query', sa.Text(), nullable=True),
    sa.Column('structured_filters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('listing_limit', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_profiles',
    sa.Column('vin', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('trim', sa.Text(), nullable=True),
    sa.Column('mileage_km', sa.Integer(), nullable=True),
    sa.Column('canonical_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('identity_status', sa.Text(), nullable=False),
    sa.Column('field_sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_snapshots',
    sa.Column('search_run_id', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Text(), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('trim', sa.Text(), nullable=True),
    sa.Column('vin', sa.Text(), nullable=True),
    sa.Column('mileage_km', sa.Integer(), nullable=True),
    sa.Column('body_style', sa.Text(), nullable=True),
    sa.Column('drivetrain', sa.Text(), nullable=True),
    sa.Column('asking_price_cad', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('location_city', sa.Text(), nullable=True),
    sa.Column('location_province', sa.Text(), nullable=True),
    sa.Column('seller_type', sa.Text(), nullable=False),
    sa.Column('deal_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('is_overpriced', sa.Boolean(), nullable=False),
    sa.Column('pricing_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('risk_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('relevance_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('relevance_reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('image_urls', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('image_risk_adjustment', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('image_risk_reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('confidence_by_section', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_run_id'], ['search_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dealer_settings',
    sa.Column('dealer_account_id', sa.String(), nullable=False),
    sa.Column('default_target_profit_cad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('risk_tolerance', sa.Text(), nullable=False),
    sa.Column('preferred_brands', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('preferred_models', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('default_search_radius_km', sa.Integer(), nullable=False),
    sa.Column('include_overpriced_default', sa.Boolean(), nullable=False),
    sa.Column('candidate_score_threshold', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_candidate_count', sa.Integer(), nullable=False),
    sa.Column('max_images_per_candidate', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dealer_account_id'], ['dealer_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dealer_account_id')
    )
    op.create_table('listing_snapshots',
    sa.Column('listing_id', sa.String(), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('asking_price_cad', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('mileage_km', sa.Integer(), nullable=True),
    sa.Column('location_city', sa.Text(), nullable=True),
    sa.Column('location_province', sa.Text(), nullable=True),
    sa.Column('seller_type', sa.Text(), nullable=False),
    sa.Column('vin', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('trim', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.Text(), nullable=False),
    sa.Column('extraction_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('extracted_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searches',
    sa.Column('dealer_account_id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('natural_language_query', sa.Text(), nullable=True),
    sa.Column('structured_filters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('location_city', sa.Text(), nullable=True),
    sa.Column('location_province', sa.Text(), nullable=False),
    sa.Column('radius_km', sa.Integer(), nullable=False),
    sa.Column('listing_limit', sa.Integer(), nullable=False),
    sa.Column('include_overpriced', sa.Boolean(), nullable=False),
    sa.Column('target_profit_cad', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('risk_tolerance', sa.Text(), nullable=True),
    sa.Column('scheduled', sa.Boolean(), nullable=False),
    sa.Column('schedule_cron', sa.Text(), nullable=True),
    sa.Column('alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('in_app_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dealer_account_id'], ['dealer_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('dealer_account_id', sa.String(), nullable=False),
    sa.Column('listing_id', sa.String(), nullable=True),
    sa.Column('latest_listing_snapshot_id', sa.String(), nullable=True),
    sa.Column('vehicle_profile_id', sa.String(), nullable=True),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('deal_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('preliminary', sa.Boolean(), nullable=False),
    sa.Column('missing_key_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_overpriced', sa.Boolean(), nullable=False),
    sa.Column('candidate_selected', sa.Boolean(), nullable=False),
    sa.Column('seller_contact_status', sa.Text(), nullable=True),
    sa.Column('seller_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dealer_account_id'], ['dealer_accounts.id'], ),
    sa.ForeignKeyConstraint(['latest_listing_snapshot_id'], ['listing_snapshots.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['vehicle_profile_id'], ['vehicle_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparable_listings',
    sa.Column('opportunity_id', sa.String(), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('trim', sa.Text(), nullable=True),
    sa.Column('mileage_km', sa.Integer(), nullable=True),
    sa.Column('asking_price_cad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('similarity_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('included', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_reports',
    sa.Column('opportunity_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('report_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('confidence_by_section', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('pdf_object_key', sa.Text(), nullable=True),
    sa.Column('csv_object_key', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_analyses',
    sa.Column('opportunity_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('comparable_count', sa.Integer(), nullable=False),
    sa.Column('retail_low_cad', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('retail_mid_cad', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('retail_high_cad', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_buy_price_cad', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('starting_offer_cad', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('calculation_inputs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'version')
    )
    op.create_table('risk_analyses',
    sa.Column('opportunity_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('risk_level', sa.Text(), nullable=False),
    sa.Column('risk_factors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('missing_verifications', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_analyses')
    op.drop_table('pricing_analyses')
    op.drop_table('decision_reports')
    op.drop_table('comparable_listings')
    op.drop_table('opportunities')
    op.drop_table('searches')
    op.drop_table('listing_snapshots')
    op.drop_table('dealer_settings')
    op.drop_table('candidate_snapshots')
    op.drop_table('vehicle_profiles')
    op.drop_table('search_runs')
    op.drop_table('listings')
    op.drop_table('dealer_accounts')
    # ### end Alembic commands ###
